import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-be-vietnam',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Crash Compass",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: '/CCFavV1.svg', type: 'image/svg+xml' }],
    shortcut: '/CCFavV1.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={beVietnamPro.className}>
      <body className="antialiased">
        <Header />
        {children}
        <footer className="text-center text-sm text-accent/70 mb-10">
          &copy; {new Date().getFullYear()} CrashCompass. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
